# Generated by Django 3.0.5 on 2020-06-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna_nombre', models.CharField(db_index=True, max_length=100)),
                ('fecha', models.CharField(max_length=20)),
                ('fk_comuna', models.PositiveSmallIntegerField(db_index=True, verbose_name='fk_comuna')),
                ('fk_region', models.PositiveSmallIntegerField(db_index=True, verbose_name='fk_region')),
                ('funcionamiento_dia', models.CharField(max_length=20)),
                ('funcionamiento_hora_apertura', models.CharField(max_length=20)),
                ('funcionamiento_hora_cierre', models.CharField(max_length=20)),
                ('local_direccion', models.CharField(max_length=150)),
                ('local_id', models.PositiveSmallIntegerField(verbose_name='local_id')),
                ('local_lat', models.CharField(max_length=20)),
                ('local_lng', models.CharField(max_length=20)),
                ('local_nombre', models.CharField(max_length=100)),
                ('local_telefono', models.CharField(max_length=20)),
                ('localidad_nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
            },
        ),
    ]
