# Generated by Django 3.0.5 on 2020-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='local_id',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='local_id'),
        ),
    ]
